// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/custom/mongops (interfaces: CRUD)

// Package mongops is a generated GoMock package.
package mongops

import (
        gomock "github.com/golang/mock/gomock"
        mgo_v2 "gopkg.in/mgo.v2"
        reflect "reflect"
)

// MockCRUD is a mock of CRUD interface
type MockCRUD struct {
        ctrl     *gomock.Controller
        recorder *MockCRUDMockRecorder
}

// MockCRUDMockRecorder is the mock recorder for MockCRUD
type MockCRUDMockRecorder struct {
        mock *MockCRUD
}

// NewMockCRUD creates a new mock instance
func NewMockCRUD(ctrl *gomock.Controller) *MockCRUD {
        mock := &MockCRUD{ctrl: ctrl}
        mock.recorder = &MockCRUDMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockCRUD) EXPECT() *MockCRUDMockRecorder {
        return m.recorder
}

// InsertRecord mocks base method
func (m *MockCRUD) InsertRecord(arg0 mgo_v2.Collection) error {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "InsertRecord", arg0)
        ret0, _ := ret[0].(error)
        return ret0
}

// InsertRecord indicates an expected call of InsertRecord
func (mr *MockCRUDMockRecorder) InsertRecord(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRecord", reflect.TypeOf((*MockCRUD)(nil).InsertRecord), arg0)
}